import './globals.css'
import Header from '../components/Header'
import Providers from '@/components/Providers'
// import { Inter } from 'next/font/google'

// const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'IMDb Clone',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Providers> 

          <Header/>

          
          {children}
          
        </Providers>
      </body>
    </html>
  )
}
